language: python
sudo: required
services:
  - docker

install:
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get update
  - sudo apt-get -y install
         pep8
  - sudo pip install
         astroid==1.2.1
         isort==3.9.0
         pylint==1.3.1

script:
 - make check
 - docker run -it -v /var/run/docker.sock:/var/run/docker.sock:ro
     -v $PWD:/src:ro --workdir=/src stbtester/stbt-docker-selftest
     tests/run-tests.sh tests/test-stbt-docker.sh
